# Generated by Django 4.1.3 on 2022-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', '正常'), ('r', '已預訂'), ('l', '借出中'), ('m', '維修中')], default='n', max_length=10)),
                ('production_time', models.DateField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('Insurance_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('type_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('maximum_load', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'None')], default='m', max_length=1)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('p', '未付款'), ('np', '已付款')], default='np', max_length=10)),
                ('order_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.car')),
                ('order_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.station')),
                ('order_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.user')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.cartype'),
        ),
    ]
