# Generated by Django 4.1.3 on 2022-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
