# Generated by Django 4.1.3 on 2022-12-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
