# Generated by Django 4.1.3 on 2022-12-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('p', '未付款'), ('np', '已付款')], default='np', max_length=10)),
                ('order_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.car')),
                ('order_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.station')),
                ('order_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.user')),
            ],
        ),
    ]
