# Generated by Django 4.1.3 on 2022-12-07 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unlock_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
