# Generated by Django 4.1.3 on 2022-12-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0004_order_unlock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_car_time', models.DateTimeField()),
                ('return_car_time', models.DateTimeField()),
                ('pay', models.IntegerField()),
                ('transaction_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.car')),
                ('transaction_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.station')),
            ],
        ),
    ]
