# Generated by Django 4.1.3 on 2022-12-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0006_remove_order_order_station_car_locate_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.station'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.user'),
        ),
        migrations.AlterField(
            model_name='car',
            name='locate_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rent.station'),
        ),
    ]
