# Generated by Django 4.1.3 on 2022-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0008_transaction_transaction_id_alter_car_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AddField(
            model_name='order',
            name='order_return_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_use_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男生'), ('女', '女生'), ('其他', '其他')], default='其他', max_length=8),
        ),
    ]
