# Generated by Django 4.1.3 on 2022-12-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0011_alter_order_order_return_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_car",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
