# Generated by Django 4.1.3 on 2022-12-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0012_alter_transaction_transaction_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_station",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
